name: install testmo cli
description: 'install testmo cli'
runs:
  using: composite
  steps:
    - id: testmo_install
      run: |
        sudo mkdir -p /usr/local/apps
        sudo chown -R $(whoami):$(whoami) /usr/local/apps
        export XDG_CONFIG_HOME=/usr/local/apps
        cd /usr/local/apps
        curl -o- --retry 8 --retry-delay 16 --retry-max-time 600 https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
        export NVM_DIR='/usr/local/apps/nvm'
        [ -s "/usr/local/apps/nvm/nvm.sh" ] && \. "/usr/local/apps/nvm/nvm.sh"; \
        nvm install 19; \
        npm install --global --save-prod @testmo/testmo-cli
      shell: bash
