name: set up caches
description: 'set up HF and Python caches'
runs:
  using: composite
  steps:
  - run: |
      sudo mkdir -m 777 -p ${HF_HOME}
      sudo chown -R $(whoami):$(whoami) ${HF_HOME}
      sudo mkdir -m 777 -p ${PIP_CACHE_DIR}
      sudo chown -R $(whoami):$(whoami) ${PIP_CACHE_DIR}
    shell: bash
