name: test neuralmagic-vllm
description: "test neuralmagic-vllm via, 'pytest tests/'"
inputs:
  test_directory:
    description: 'test directory, path is relative to neuralmagic-vllm'
    required: true
  test_results:
    description: 'top-level directory for xml test results'
    required: true
  python:
    description: 'python version, e.g. 3.10.12'
    required: true
  venv:
    description: 'name for python virtual environment'
    required: true
  pypi:
    description: 'ip address for pypi server'
    required: true
outputs:
  status:
    description: "final status from 'pytest tests/'"
    value: ${{ steps.test.outputs.status }}
runs:
  using: composite
  steps:
  - id: test
    run: |
      COMMIT=${{ github.sha }}
      VENV="${{ inputs.venv }}-${COMMIT:0:7}"
      source $(pyenv root)/versions/${{ inputs.python }}/envs/${VENV}/bin/activate
      pip3 install --index-url http://${{ inputs.pypi }}:8080/ --trusted-host ${{ inputs.pypi }} magic-wand
      pip3 install -r requirements-dev.txt
      # run tests via runner script (serially)
      SUCCESS=0
      ./.github/scripts/run-tests -t ${{ inputs.test_directory }} -r ${{ inputs.test_results }} || SUCCESS=$?
      echo "was this a SUCCESS? ${SUCCESS}"
      echo "status=${SUCCESS}" >> "$GITHUB_OUTPUT"
      exit ${SUCCESS}
    shell: bash
