name: test neuralmagic-vllm
description: "test neuralmagic-vllm via, 'pytest tests/'"
inputs:
  test_directory:
    description: 'test directory, path is relative to magic_wand'
    required: true
  test_xml:
    description: 'filename for xml test results'
    required: true
outputs:
  status:
    description: "final status from 'pytest tests/'"
    value: ${{ steps.test.outputs.status }}
runs:
  using: composite
  steps:
  - id: test
    run: |
      SUCCESS=0
      # TODO: this is a hack ... fix it later
      # pyenv hardcoded ... python version hardcoded ...
      source $(pyenv root)/versions/3.10.12/envs/TEST/bin/activate
      pip3 install --index-url http://192.168.201.226:8080/ --trusted-host 192.168.201.226 magic-wand
      pip3 install -r requirements-dev.txt
      pytest --junitxml=${{ inputs.test_xml }} ${{ inputs.test_directory }} || SUCCESS=$?
      echo "status=${SUCCESS}" >> "$GITHUB_OUTPUT"
      exit ${SUCCESS}
    shell: bash
