name: cp assets
description: "cp whl and tarfile to Google storage 'neuralmagic-public-pypi/dist'"
inputs:
  whl:
    description: "the wheel asset file path"
    required: true
  targz:
    description: "the tar.gz asset file path"
    required: true
runs:
  using: composite
  steps:
    - id: cp_assets
      run: |
        gcloud storage cp ${WHL} gs://neuralmagic-public-pypi/dist/${{ inputs.whl }}
        gcloud storage cp ${TAR} gs://neuralmagic-public-pypi/dist/${{ inputs.targz }}
      shell: bash
