name: install and test whl
description: 'install whl in venv and run tests'
inputs:
  python:
    description: 'python version, e.g. 3.10.12'
    required: true
  venv:
    description: 'name for python virtual environment'
    required: true
  whl:
    description: 'filepath for magic_wand whl file'
    required: true
  test_skip_list:
    description: 'file containing tests to skip'
    required: true
  test_directory:
    description: 'directory to test files'
    required: true
  test_results:
    description: 'desired directory for test results'
    required: true
outputs:
  status:
    description: 'return test result'
    value: ${{ steps.whl_install_test.outputs.status }}
runs:
  using: composite
  steps:
    - id: whl_install_test
      run: |
        COMMIT=${{ github.sha }}
        VENV="${{ inputs.venv }}-${COMMIT:0:7}"
        pyenv virtualenv ${VENV}
        source $(pyenv root)/versions/${{ inputs.python }}/envs/${VENV}/bin/activate
        pip3 install coverage
        pip3 list
        ls -alh dist
        pip3 install ${{ inputs.whl }}
        pip3 install -r requirements-dev.txt
        SUCCESS=0
        ./.github/scripts/run-tests -t ${{ inputs.test_directory }} -r ${{ inputs.test_results }} -f ${{ inputs.test_skip_list }}|| SUCCESS=$?
        echo "status=${SUCCESS}" >> "$GITHUB_OUTPUT"
        exit ${SUCCESS}
      shell: bash
