name: HF cache
description: 'mount HF cache'
inputs:
  fs_cache:
    description: '(deprecated) filesystem to use for HF cache'
    required: true
runs:
  using: composite
  steps:
  - run: |
      sudo mkdir -m 777 -p ${HF_HOME}
      sudo chown -R $(whoami):$(whoami) ${HF_HOME}
    shell: bash
