name: summary whl
description: 'creates a summary for whl workflow'
inputs:
  label:
    description: 'GHA runner label'
    required: true
  gitref:
    description: 'git commit hash or branch name'
    required: true
  testmo_run_url:
    description: 'testmo URL for this particular run'
    required: true
  python:
    description: 'python version info'
    required: true
  whl:
    description: 'whl file tested'
    required: true
  tarball:
    description: 'tar.gz file tested'
    required: true
runs:
  using: composite
  steps:
  - run: |
      TESTMO_URL=${{ inputs.testmo_run_url }}
      TEST_STATUS=${{ inputs.test_status }}
      TEST_EMOJI=$(./.github/scripts/step-status ${TEST_STATUS})
      echo "testmo URL: ${TESTMO_URL}" >> $GITHUB_STEP_SUMMARY
      echo ""
      echo "| Parameter | |" >> $GITHUB_STEP_SUMMARY
      echo "|---|---|" >> $GITHUB_STEP_SUMMARY
      echo "| label: | \`${{ inputs.label }}\` |" >> $GITHUB_STEP_SUMMARY
      echo "| git sha: | \`${{ github.sha }}\` |" >> $GITHUB_STEP_SUMMARY
      echo "| github actor: | '${{ github.actor }}' |" >> $GITHUB_STEP_SUMMARY
      echo "| gitref: | '${{ inputs.gitref }}' |" >> $GITHUB_STEP_SUMMARY
      echo "| branch name: | '${{ github.ref_name }}' |" >> $GITHUB_STEP_SUMMARY
      echo "| python: | ${{ inputs.python }} |" >> $GITHUB_STEP_SUMMARY
      echo "| whl: | ${{ inputs.whl }} |" >> $GITHUB_STEP_SUMMARY
      echo "| tarball: | ${{ inputs.tarball }} |" >> $GITHUB_STEP_SUMMARY
    shell: bash
