name: set up nvidia-container-toolkit for docker
description: 'sets up nvidia-container-toolkit for docker'
runs:
  using: composite
  steps:
  - run: |
        # install nvidia-container-toolkit
        curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
          && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
          sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
          sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
        sudo sed -i -e '/experimental/ s/^#//g' /etc/apt/sources.list.d/nvidia-container-toolkit.list
        sudo killall apt apt-get || echo 'no apt or apt-get process to kill'
        sudo apt-get update
        sudo apt-get install -y nvidia-container-toolkit
        # config and restart docker
        sudo systemctl stop docker
        sudo nvidia-ctk runtime configure --runtime=docker
        sudo systemctl start docker
    shell: bash
