name: install whl
description: 'installs found whl based on python version into specified venv'
inputs:
  python:
    description: 'python version, e.g. 3.10.12'
    required: true
  venv:
    description: 'name for python virtual environment'
    required: true
runs:
  using: composite
  steps:
    - id: install_whl
      run: |
        # move source directories
        mv vllm vllm-ignore
        mv csrc csrc-ignore
        # activate and install
        if [ ! -z "${{ inputs.venv }}" ]; then
          COMMIT=${{ github.sha }}
          VENV="${{ inputs.venv }}-${COMMIT:0:7}"
          source $(pyenv root)/versions/${{ inputs.python }}/envs/${VENV}/bin/activate
        fi
        pip3 install -r requirements-dev.txt
        WHL=$(find . -type f -iname "nm_vllm*.whl")
        WHL_BASENAME=$(basename ${WHL})
        echo "whl=${WHL_BASENAME}" >> "$GITHUB_OUTPUT"
        pip3 install ${WHL}[sparse] --extra-index-url https://pypi.neuralmagic.com/simple
        # report magic_wand version
        MAGIC_WAND=$(pip3 show nm-magic-wand-nightly | grep "Version" | cut -d' ' -f2) || echo "nightly not installed"
        if [ -z "${MAGIC_WAND}" ]; then
          # if neither magic-wand nor magic-wand-nightly is installed stop here with error
          MAGIC_WAND=$(pip3 show nm-magic-wand | grep "Version" | cut -d' ' -f2)
        fi
        echo "magic_wand=${MAGIC_WAND}" >> "$GITHUB_OUTPUT"
      shell: bash
