name: Get additinal docker image tag based on build type
description: 'docker image tag for nm-vllm'
inputs:
  build_type:
    description: "type of nm-vllm to install for the docker image: NIGHTLY (default) or RELEASE"
    type: string
    default: 'NIGHTLY'
outputs:
  tag:
    description: "extra tag for the docker image based on build type"
    value: ${{ steps.extratag.outputs.tag }}
runs:
  using: composite
  steps:
  - id: extratag
    run: |
      tag=nightly
      if [[ "${{ inputs.build_type }}" = "RELEASE" ]]; then
          tag=latest
      fi
      echo "tag=${tag}" >> $GITHUB_OUTPUT
    shell: bash
