#include <torch/extension.h>

#define CUTLASS3X_DEFS\
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x2x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x2x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x2x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x8x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x8x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x8x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_4x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_4x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_4x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_2x1x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_2x1x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_2x1x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x2x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x2x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x2x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x8x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x8x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x8x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_4x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_4x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_4x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_2x1x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_2x1x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_2x1x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x2x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x2x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x2x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x8x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x8x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x8x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_4x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_4x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_4x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_2x1x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_2x1x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_2x1x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x2x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x2x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x2x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x8x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x8x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x8x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_4x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_4x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_4x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8"); \
 ops.def("autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_2x1x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8", &autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_2x1x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8, "autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_2x1x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8"); \


void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x2x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x8x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_4x4x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_2x1x1_KernelTmaWarpSpecializedFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x256_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x64x128_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x256_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x2x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x8x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_1x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_4x4x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_64x128x128_2x1x1_KernelTmaWarpSpecializedPingpongFP8FastAccum_TmaWarpSpecialized_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x2x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x8x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_4x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_2x1x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x2x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x8x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_4x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_2x1x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_PersistentScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x2x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x8x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_1x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_4x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x128x128_2x1x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x2x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x8x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_1x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_4x4x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);

void autogen_cutlass3x_scaled_mm_dq_sm90_128x64x128_2x1x1_KernelTmaWarpSpecializedCooperativeFP8FastAccum_TmaWarpSpecializedCooperative_StreamKScheduler_kGemm_fp8(torch::Tensor &out, torch::Tensor const &a,
                torch::Tensor const &b,
                torch::Tensor const &a_scales,
                torch::Tensor const &b_scales);
