name: run coverage_report_breakdown
description: 'run coverage_report_breakdown to generate markdown showing test coverage breakdown'
inputs:
  coverage_json:
    description: 'file containing coverage report in JSON format'
    required: true
runs:
  using: composite
  steps:
    - id: coverage_report_breakdown
      run: |
        # the pandas.DataFrame.to_markdown() method requires the `tabulate` package
        pip3 install tabulate
        # prepare a multiline response to pass to github_output
        echo 'COVERAGE_MD<<EOF'
        python3 ./.github/scripts/coverage_report_breakdown.py ${{ inputs.coverage_json }}
        echo EOF
        echo "markdown=${COVERAGE_MD}" >> $GITHUB_OUTPUT
      shell: bash
