name: set python
description: 'sets python version and creates venv for neuralmagic'
inputs:
  python:
    description: 'python version, e.g. 3.10.12'
    required: true
  venv:
    description: 'name for python virtual environment'
    required: true
outputs:
  version:
    description: "result from 'python --version'"
    value: ${{ steps.set_python.outputs.version }}
runs:
  using: composite
  steps:
    - id: set_python
      run: |
        command -v pyenv
        pyenv local ${{ inputs.python }}
        COMMIT=${{ github.sha }}
        VENV="${{ inputs.venv }}-${COMMIT:0:7}"
        pyenv virtualenv --force ${VENV}
        source $(pyenv root)/versions/${{ inputs.python }}/envs/${VENV}/bin/activate
        VERSION=$(python --version)
        echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
      shell: bash
