name: set neuralmagic env
description: 'sets environment variables for neuralmagic'
runs:
  using: composite
  steps:
  - run: |
      # echo "TORCH_CUDA_ARCH_LIST=8.0+PTX" >> $GITHUB_ENV
      echo "PYENV_ROOT=/usr/local/apps/pyenv" >> $GITHUB_ENV
      echo "XDG_CONFIG_HOME=/usr/local/apps" >> $GITHUB_ENV
      WHOAMI=$(whoami)
      echo "PATH=/usr/local/apps/pyenv/plugins/pyenv-virtualenv/shims:/usr/local/apps/pyenv/shims:/usr/local/apps/pyenv/bin:/usr/local/apps/nvm/versions/node/v16.20.2/bin:/usr/local/cuda-12.1/bin:/usr/local/cuda-12.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/${WHOAMI}/.local/bin:" >> $GITHUB_ENV
      echo "LD_LIBRARY_PATH=/usr/local/cuda-12.1/lib64::/usr/local/cuda-12.1/lib64:" >> $GITHUB_ENV
      echo "PROJECT_ID=12" >> $GITHUB_ENV
    shell: bash
