name: test whl
description: 'run tests on installed whl'
inputs:
  test_skip_list:
    description: 'file containing tests to skip'
    required: true
  test_directory:
    description: 'directory to test files'
    required: true
  test_results:
    description: 'desired directory for test results'
    required: true
outputs:
  status:
    description: 'return test result'
    value: ${{ steps.test_whl.outputs.status }}
runs:
  using: composite
  steps:
    - id: test_whl
      run: |
        pip3 install coverage
        pip3 install pytest-cov
        pip3 install pytest-xdist
        pip3 install -r requirements-dev.txt
        # SUCCESS=0
        # VLLM_SRC=$(python3 -c "import vllm; print(vllm.__path__[0])")
        # sudo ./.github/scripts/run-tests -s ${VLLM_SRC} -t ${{ inputs.test_directory }} -r ${{ inputs.test_results }} -f ${{ inputs.test_skip_list }}|| SUCCESS=$?
        # echo "status=${SUCCESS}" >> "$GITHUB_OUTPUT"
        # exit ${SUCCESS}
      shell: bash
