name: build neuralmagic-vllm
description: 'build neuralmagic-vllm'
inputs:
  Gi_per_thread:
    description: 'requested Gi to reserve per thread'
    required: true
outputs:
  status:
    description: "final build status from 'pip install -e'"
    value: ${{ steps.build.outputs.status }}
runs:
  using: composite
  steps:
  - id: build
    run: |
      pip install -r requirements.txt
      SUCCESS=0
      pip install -e . || SUCCESS=$?
      echo "status=${SUCCESS}" >> "$GITHUB_OUTPUT"
      exit ${SUCCESS}
    shell: bash
