name: run vllm benchmarks
description: 'run vllm benchmarks'
inputs:
  output_directory:
    description: 'output directory to store the benchmark results'
    required: true
runs:
  using: composite
  steps:
  - id: benchmark
    run: |
      export NM_BENCHMARK_OUTPUT_DIR=${{ inputs.output_directory }}
      export PYTHONPATH=$PYTHONPATH:./
      mkdir -p ${{ inputs.output_directory }}
      SUCCESS=0
      .github/workflows/scripts/run_benchmarks ${{ inputs.output_directory }} || SUCCESS=$1
      echo "test=${SUCCESS}" >> "$GITHUB_OUTPUT"
      exit ${SUCCESS}
    shell: bash