{
 "title": "nm-vllm",
 "description": "nm-vllm Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Request Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time Per Output Token",
   "type": "timeseries",
   "description": "Histogram of next token latency measured in ms.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, vllm:time_per_output_token_seconds_bucket)",
     "legendFormat": "P99 Latency"
    },
    {
     "expr": "histogram_quantile(0.95, vllm:time_per_output_token_seconds_bucket)",
     "legendFormat": "P95 Latency"
    },
    {
     "expr": "histogram_quantile(0.5, vllm:time_per_output_token_seconds_bucket)",
     "legendFormat": "P50 Latency"
    }
   ]
  },
  {
   "title": "Time To First Token",
   "type": "timeseries",
   "description": "Histogram of first token latency measured in ms.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, vllm:time_to_first_token_seconds_bucket)",
     "legendFormat": "P99 Latency"
    },
    {
     "expr": "histogram_quantile(0.95, vllm:time_to_first_token_seconds_bucket)",
     "legendFormat": "P95 Latency"
    },
    {
     "expr": "histogram_quantile(0.5, vllm:time_to_first_token_seconds_bucket)",
     "legendFormat": "P50 Latency"
    }
   ]
  },
  {
   "title": "E2E Request Latency",
   "type": "timeseries",
   "description": "Histogram of end-to-end request latency measured in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, vllm:e2e_request_latency_seconds_bucket)",
     "legendFormat": "P99 Latency"
    },
    {
     "expr": "histogram_quantile(0.9, vllm:e2e_request_latency_seconds_bucket)",
     "legendFormat": "P90 Latency"
    },
    {
     "expr": "histogram_quantile(0.5, vllm:e2e_request_latency_seconds_bucket)",
     "legendFormat": "P50 Latency"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Generation Token Throughput ",
   "type": "timeseries",
   "description": "Total number of generation tokens processed per second over an interval",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(vllm:generation_tokens_total[$__rate_interval])",
     "legendFormat": "Tokens/sec"
    }
   ]
  },
  {
   "title": "Prompt Token Throughput",
   "type": "timeseries",
   "description": "Total number of prompt tokens processed per second over an interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "rate(vllm:prompt_tokens_total[$__rate_interval])",
     "legendFormat": "Tokens/sec"
    }
   ]
  },
  { "title": "System State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Scheduler State",
   "type": "timeseries",
   "description": "Number of requests in running, waiting, and swapped states",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    { "expr": "vllm:num_requests_running", "legendFormat": "Number of Running Requests" },
    { "expr": "vllm:num_requests_waiting", "legendFormat": "Number of Waiting Requests" },
    { "expr": "vllm:num_requests_swapped", "legendFormat": "Number of Swapped Requests" }
   ]
  },
  {
   "title": "KV Cache Utilization",
   "type": "timeseries",
   "description": "Percentage of KV cache blocks in use",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "vllm:gpu_cache_usage_perc", "legendFormat": "GPU KV Cache Usage" },
    { "expr": "vllm:cpu_cache_usage_perc", "legendFormat": "CPU KV Cache Usage" }
   ]
  }
 ]
}