name: build-test
on:
  # makes workflow reusable
  workflow_call:
    inputs:
      build_label:
        description: "requested runner label (specifies instance)"
        type: string
        required: true
      timeout:
        description: "time limit for run in minutes "
        type: string
        required: true
      gitref:
        description: "git commit hash or branch name"
        type: string
        required: true
      Gi_per_thread:
        description: 'requested GiB to reserve per thread'
        type: string
        required: true
      nvcc_threads:
        description: "number of threads nvcc build threads"
        type: string
        required: true
      python:
        description: "python version, e.g. 3.10.12"
        type: string
        required: true
      test_skip_list:
        description: 'file containing tests to skip'
        type: string
        required: true

  # makes workflow manually callable
  workflow_dispatch:
    inputs:
      build_label:
        description: "requested runner label (specifies instance)"
        type: string
        required: true
      timeout:
        description: "time limit for run in minutes "
        type: string
        required: true
      gitref:
        description: "git commit hash or branch name"
        type: string
        required: true
      Gi_per_thread:
        description: 'requested GiB to reserve per thread'
        type: string
        required: true
      nvcc_threads:
        description: "number of threads nvcc build threads"
        type: string
        required: true
      python:
        description: "python version, e.g. 3.10.12"
        type: string
        required: true
      test_skip_list:
        description: 'file containing tests to skip'
        type: string
        required: true

jobs:

    BUILD:
        uses: ./.github/workflows/build.yml
        with:
            build_label: ${{ inputs.build_label }}
            timeout: ${{ inputs.timeout }}
            gitref: ${{ inputs.gitref }}
            Gi_per_thread: ${{ inputs.Gi_per_thread }}
            nvcc_threads: ${{ inputs.nvcc_threads }}
            python: ${{ inputs.python }}
        secrets: inherit

    TEST:
        needs: [BUILD]
        if: success()
        strategy:
            matrix:
                test_label: [aws-avx2-192G-4-a10g-96G]
        uses: ./.github/workflows/test.yml
        with:
            test_label: ${{ matrix.test_label }}
            timeout: ${{ inputs.timeout }}
            gitref: ${{ inputs.gitref }}
            python: ${{ inputs.python }}
            whl: ${{ needs.BUILD.outputs.whl }}
            test_skip_list: ${{ inputs.test_skip_list }}
        secrets: inherit
