name: Manual Docker Build

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
    build-docker-image:

        runs-on: aws-avx2-32G-a10g-24G
        timeout-minutes: 60

        steps:

          - name: checkout
            id: checkout
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
              ref: ${{ inputs.gitref }}
              submodules: recursive

          - name: Build Docker Image
            uses: docker/build-push-action@v2
            with:
              context: .
              load: true  # Ensures image is loaded into Docker daemon but not pushed
