name: Nightly
run-name: ${{ github.actor }} triggered nightly on ${{ github.ref }}
on:
    schedule:
      # * is a special character in YAML so you have to quote this string
      - cron: '0 0 * * *'

    workflow_dispatch:

jobs:

    # All models we are benchmarking now can fit in a single GPU. Add
    # multi-gpu job when needed

    # single gpu
    AWS-AVX2-32G-A10G-24G:
        strategy:
            matrix:
                python: [3.11.4]
        uses: ./.github/workflows/nm-benchmark.yml
        with:
            label: aws-avx2-32G-a10g-24G
            benchmark_config_list_file:  ./.github/data/nm_benchmark_configs_list.txt
            timeout: 300
            gitref: '${{ github.ref }}'
            python: ${{ matrix.python }}
        secrets: inherit
