name: commit main
run-name: ${{ github.actor }} commit to main
on:
  push:
    branches:
      - main

jobs:

    # multi-gpu
    AWS-AVX2-192G-4-A10G-96G:
        strategy:
            matrix:
                python: [3.10.12]
        uses: ./.github/workflows/nm-benchmark.yml
        with:
            label: aws-avx2-192G-4-a10g-96G
            benchmark_config_list_file:  ./.github/data/nm_benchmark_configs_list.txt
            timeout: 300
            gitref: '${{ github.ref }}'
            python: ${{ matrix.python }}
        secrets: inherit

    # single gpu
    AWS-AVX2-32G-A10G-24G:
        strategy:
            matrix:
                python: [3.11.4]
        uses: ./.github/workflows/nm-benchmark.yml
        with:
            label: aws-avx2-32G-a10g-24G
            benchmark_config_list_file:  ./.github/data/nm_benchmark_configs_list.txt
            timeout: 300
            gitref: '${{ github.ref }}'
            python: ${{ matrix.python }}
        secrets: inherit