name: nm publish whl
run-name: ${{ github.actor }} publishing whl on branch '${{ github.ref}}'
on:
    workflow_dispatch:
        inputs:
            label:
                description: "requested runner label (specifies instance)"
                type: string
                required: true
            timeout:
                description: "time limit for run in minutes "
                type: string
                required: true
            gitref:
                description: 'git commit hash or branch name'
                type: string
                required: true
            python:
                description: "python version, e.g. 3.10.12"
                type: string
                required: true
            whl:
                description: "whl to test (variable appears late binding so unusable outside 'download artifact')"
                type: string
                required: true
            tarfile:
                description: "source distribution (variable appears late binding so unusable outside 'download artifact')"
                type: string
                required: true

    workflow_call:
        inputs:
            label:
                description: "requested runner label (specifies instance)"
                type: string
                required: true
            timeout:
                description: "time limit for run in minutes "
                type: string
                required: true
            gitref:
                description: 'git commit hash or branch name'
                type: string
                required: true
            python:
                description: "python version, e.g. 3.10.12"
                type: string
                required: true
            whl:
                description: "whl to test (variable appears late binding so unusable outside 'download artifact')"
                type: string
                required: true
            tarfile:
                description: "source distribution (variable appears late binding so unusable outside 'download artifact')"
                type: string
                required: true

jobs:

    PUBLISH:
        runs-on: ${{ inputs.label }}
        timeout-minutes: ${{ fromJson(inputs.timeout) }}

        steps:

            - name: checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                ref: ${{ inputs.gitref }}
                submodules: recursive

            - name: setenv
              id: setenv
              uses: ./.github/actions/nm-set-env/

            - name: set python
              id: set_python
              uses: ./.github/actions/nm-set-python/
              with:
                python: ${{ inputs.python }}
                venv: UPLOAD
