name: nm upload assets
run-name: ${{ github.actor }} publishing whl on branch '${{ github.ref}}'
on:

    workflow_call:
        inputs:
            label:
                description: "requested runner label (specifies instance)"
                type: string
                required: true
            timeout:
                description: "time limit for run in minutes "
                type: string
                required: true
            gitref:
                description: 'git commit hash or branch name'
                type: string
                required: true
            wf_category:
                description: "workflow category: REMOTE, NIGHTLY, RELEASE"
                type: string
                default: "REMOTE"

    workflow_dispatch:
        inputs:
            label:
                description: "requested runner label (specifies instance)"
                type: string
                required: true
            timeout:
                description: "time limit for run in minutes "
                type: string
                required: true
            gitref:
                description: 'git commit hash or branch name'
                type: string
                required: true
            wf_category:
                description: "workflow category: REMOTE, NIGHTLY, RELEASE"
                type: string
                default: "REMOTE"

jobs:

    PUBLISH:
        runs-on: ${{ inputs.label }}
        timeout-minutes: ${{ fromJson(inputs.timeout) }}

        permissions:
            contents: 'read'
            id-token: 'write'

        steps:

            - name: install automation components
              run: |
                sudo apt-get update --fix-missing
                sudo apt-get install -y git-all
                sudo apt-get install -y curl

            - name: checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                ref: ${{ inputs.gitref }}
                submodules: recursive

            - name: setenv
              id: setenv
              uses: ./.github/actions/nm-set-env/

            - name: download assets
              id: download_whl
              uses: actions/download-artifact@v4
              with:
                  path: assets

            - name: get wheel and tar.gz names
              id: whl_targz_names
              uses: ./.github/actions/nm_whl_tar_gz_names

            # this workflow is only run if push-to-pypi is True, and we only
            # want to push RELEASE assets to the external pypi.org
            # publish the wheel file
            - name: push wheel to pypi.org
              if: ${{ inputs.wf_category == 'RELEASE' }}
              uses: neuralmagic/nm-actions/actions/publish_whl/action.yml@v1.0.0
              with:
                username: ${{ secrets.PYPI_PUBLIC_USER }}
                password: ${{ secrets.PYPI_PUBLIC_AUTH }}
                whl: ${{ steps.whl_targz_names.outputs.whl }}

            # publish the tar.gz file
            - name: push tar.gz to pypi.org
              if: ${{ inputs.wf_category == 'RELEASE' }}
              uses: neuralmagic/nm-actions/actions/publish_whl/action.yml@v1.0.0
              with:
                username: ${{ secrets.PYPI_PUBLIC_USER }}
                password: ${{ secrets.PYPI_PUBLIC_AUTH }}
                whl: ${{ steps.whl_targz_names.outputs.targz }}

            # GCP
            - name: 'Authenticate to Google Cloud'
              id: auth
              uses: google-github-actions/auth@v2.1.3
              with:
                  project_id: ${{ secrets.GCP_PROJECT }}
                  workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
                  service_account: ${{ secrets.NM_PYPI_SA }}

            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v2'
              with:
                  version: '>= 473.0.0'

            - name: cp assets
              id: cp-assets
              uses: ./.github/actions/nm-cp-assets/
              with:
                whl: ${{ steps.whl_targz_names.outputs.whl }}
                targz: ${{ steps.whl_targz_names.outputs.targz }}

            - name: trigger stratus nm-pypi update workflow to update nm-pypi index
              uses: actions/github-script@v6
              with:
                github-token: ${{ secrets.CICD_GITHUB_PAT }}
                script: |
                  const result = await github.rest.actions.createWorkflowDispatch({
                    owner: 'neuralmagic',
                    repo: 'stratus',
                    workflow_id: 'nm-pypi-update.yml',
                    ref: 'main'
                  })
                  console.log(result)
