name: nm Weekly
run-name: ${{ github.actor }} triggered weekly on ${{ github.ref }}
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '0 1 * * 0'  # weekly run (Sun)

  workflow_dispatch:
    inputs:
      push_benchmark_results_to_gh_pages:
        description: "When set to true, the workflow pushes all benchmarking results to gh-pages UI"
        type: choice
        options:
          - 'true'
          - 'false'
        default: 'false'

jobs:

  BUILD-TEST:
    uses: ./.github/workflows/nm-build-test.yml
    with:
      wf_category: WEEKLY
      python: 3.10.12
      gitref: ${{ github.ref }}

      test_label_solo: aws-avx2-32G-a10g-24G
      test_label_multi: aws-avx2-192G-4-a10g-96G
      test_timeout: 480
      test_skip_list: neuralmagic/tests/skip-for-weekly.txt

      benchmark_label: aws-avx2-32G-a10g-24G
      benchmark_config_list_file: ./.github/data/nm_benchmark_weekly_configs_list.txt
      benchmark_timeout: 720
      push_benchmark_results_to_gh_pages: "${{ github.event_name == 'schedule' || inputs.push_benchmark_results_to_gh_pages }}"
    secrets: inherit
