name: Docker Build + Publish

on:
  # For now, just manually trigger
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
    build-docker-image:

        runs-on: aws-avx2-192G-4-a10g-96G
        timeout-minutes: 240

        steps:
          
          - name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v3

          - name: Login to Github Packages
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

          - name: Checkout code
            uses: actions/checkout@v3
            with:
              fetch-depth: 1
              submodules: recursive

          - name: Get version tag
            id: extract_tag
            run: echo "tag=$(date +%Y%m%d)" >> $GITHUB_OUTPUT

          - name: Current Version Name
            run: echo ${{ steps.extract_tag.outputs.tag }}

          - name: nm-vllm latest
            uses: docker/build-push-action@v5
            with:
              context: .
              target: vllm-openai
              push: true
              tags: ghcr.io/neuralmagic/nm-vllm-openai:${{ steps.extract_tag.outputs.tag }},ghcr.io/neuralmagic/nm-vllm-openai:latest
