name: remote push
run-name: ${{ github.actor }} verifying branch '${{ github.ref }}'
on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

    AWS-AVX2-32G-A10G-24G:
        strategy:
          matrix:
            python: [3.8.17, 3.9,17, 3.10.12, 3.11.4]
        uses: ./.github/workflows/build-test.yml
        with:
          label: aws-avx2-32G-a10g-24G
          timeout: 180
          gitref: '${{ github.ref }}'
          python: ${{ matrix.python }}
