name: remote push
run-name: ${{ github.actor }} verifying branch '${{ github.ref }}'
on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

    # TODO: expand python matrix later, once CI system has matured.

    # multi-gpu
    AWS-AVX2-192G-4-A10G-96G:
        strategy:
            matrix:
                python: [3.10.12]
        uses: ./.github/workflows/build-test.yml
        with:
            label: aws-avx2-192G-4-a10g-96G
            timeout: 240
            gitref: '${{ github.ref }}'
            Gi_per_thread: 4
            python: ${{ matrix.python }}
            test_skip_list: neuralmagic/tests/skip-for-remote-push.txt
        secrets: inherit

    # Benchmarks
    #AWS-AVX2-32G-A10G-24G-Benchmark:
    #    uses: ./.github/workflows/nm-benchmark.yml
    #    with:
    #        label: aws-avx2-32G-a10g-24G
    #        benchmark_config_list_file:  ./.github/data/nm_benchmark_remote_push_configs_list.txt
    #        timeout: 60
    #        gitref: '${{ github.ref }}'
    #        Gi_per_thread: 12
    #        python: "3.10.12"
    #        push_benchmark_results_to_gh_pages: "false"
    #    secrets: inherit
